version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/currency-calculator
      - SPRING_DATASOURCE_USERNAME=currency-admin
      - SPRING_DATASOURCE_PASSWORD=currency-admin
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: currency-calculator
      POSTGRES_USER: currency-admin
      POSTGRES_PASSWORD: currency-admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    driver: local
